import type { Project } from "./types";

/**
 * Projects are grouped by `category` in the UI. External links are intentionally
 * omitted where a public/verifiable URL isn't available — add a `links: [...]`
 * entry here to surface a button on any card, no component changes required.
 */
export const projects: Project[] = [
  // ── Products ──────────────────────────────────────────────────────────────
  {
    slug: "orkaiva",
    name: "Orkaiva",
    category: "Product",
    icon: "layers",
    tagline: "Modular, multi-tenant HRM platform.",
    description: "",
    role: "Technical Lead & Architect",
    timeframe: "Adorway",
    status: "Product",
    featured: true,
    stack: ["Microservices", "Node.js", "React", "Multi-tenancy", "AWS"],
  },
  {
    slug: "copconnect",
    name: "CopConnect",
    category: "Product",
    icon: "puzzle",
    tagline: "Cyber-safety, made reachable.",
    description: "",
    role: "Architect",
    timeframe: "Adorway",
    status: "Social impact",
    featured: true,
    stack: ["React Native", "Node.js", "Secure comms"],
  },
  {
    slug: "ethixfirst",
    name: "EthixFirst",
    category: "Product",
    icon: "compass",
    tagline: "Workplace ethics & integrity.",
    description: "",
    role: "Full-Stack Engineer",
    timeframe: "Artios · 2024",
    status: "Product",
    featured: true,
    stack: ["React", "Node.js", "Workflow"],
  },
  {
    slug: "slr-astro",
    name: "SLR Astro",
    category: "Product",
    icon: "sparkles",
    tagline: "Consultations, delivered on mobile.",
    description: "",
    role: "Architect & Engineer",
    timeframe: "Adorway",
    status: "Mobile",
    stack: ["React Native", "Node.js", "Realtime"],
  },

  // ── Professional / Enterprise ────────────────────────────────────────────
  {
    slug: "cobol2java",
    name: "Cobol to Java",
    category: "Professional",
    icon: "transform",
    tagline: "Modernization intelligence for legacy systems.",
    description: "",
    role: "Technical Lead & Architect",
    timeframe: "Creospan · 2025",
    status: "Enterprise",
    featured: true,
    stack: ["COBOL", "Java", "OpenCode AI", "Validation"],
  },
  {
    slug: "credibl",
    name: "Credibl",
    category: "Professional",
    icon: "package",
    tagline: "Digital credentials at scale.",
    description: "",
    role: "Full-Stack Engineer",
    timeframe: "Artios · 2024",
    status: "Client work",
    stack: ["React", "Canvas / SVG", "Node.js"],
  },

  // ── Security ─────────────────────────────────────────────────────────────
  {
    slug: "privilegezero",
    name: "PrivilegeZero",
    category: "Security",
    icon: "shield",
    tagline: "Threat intelligence, operationalized.",
    description: "",
    role: "Architect & Engineer",
    timeframe: "Artios · 2024",
    status: "Security",
    featured: true,
    stack: ["Threat Intel", "React", "Node.js"],
  },
  {
    slug: "breachx",
    name: "BreachX",
    category: "Security",
    icon: "shield",
    tagline: "Attack-resistance & proactive defense.",
    description: "",
    role: "Architect & Engineer",
    timeframe: "Artios · 2024",
    status: "Security",
    stack: ["Vulnerability Research", "React", "Node.js"],
  },
  {
    slug: "ctem",
    name: "CTEM",
    category: "Security",
    icon: "shield",
    tagline: "Continuous Threat Exposure Management.",
    description: "",
    role: "Solution Designer",
    timeframe: "Artios · 2024",
    status: "Security",
    stack: ["Exposure Mgmt", "Automation"],
  },
  {
    slug: "malware-bucket",
    name: "Malware Bucket",
    category: "Security",
    icon: "shield",
    tagline: "Automated malware analysis.",
    description: "",
    role: "Engineer",
    timeframe: "Artios · 2024",
    status: "Security",
    stack: ["Malware Analysis", "Automation"],
  },

  // ── Open Source ──────────────────────────────────────────────────────────
  {
    slug: "react-devdotto",
    name: "React-DevDotTo",
    category: "Open Source",
    icon: "package",
    tagline: "Published NPM package for React devs.",
    description: "",
    role: "Author & Maintainer",
    timeframe: "Open source",
    status: "NPM",
    stack: ["React", "TypeScript", "NPM"],
  },

  // ── Experiments ──────────────────────────────────────────────────────────
  {
    slug: "ananta",
    name: "Ananta",
    category: "Experiment",
    icon: "puzzle",
    tagline: "A calmer new-tab, your way.",
    description: "",
    role: "Creator",
    timeframe: "Side project",
    status: "Browser extension",
    stack: ["Browser Extension", "JavaScript"],
  },
];
