import type { SkillGroup } from "./types";

export const skills: SkillGroup[] = [
  {
    label: "Languages & Frameworks",
    icon: "code",
    items: [
      "Java",
      "Spring Boot",
      "Node.js",
      "TypeScript",
      "JavaScript",
      "NestJS",
      "Express.js",
      "React.js",
      "Next.js",
      "React Native",
    ],
  },
  {
    label: "Cloud & DevOps",
    icon: "cloud",
    items: [
      "AWS (EC2, S3, IAM, Cognito, CloudFront, EKS, R2)",
      "DigitalOcean",
      "Terraform",
      "Docker",
      "Kubernetes",
      "Jenkins",
      "GitHub Actions",
      "CI/CD",
      "Firebase",
      "Jest",
    ],
  },
  {
    label: "Data & Messaging",
    icon: "server",
    items: [
      "PostgreSQL",
      "MongoDB",
      "MySQL",
      "Oracle Database",
      "DynamoDB",
      "ClickHouse",
      "ScyllaDB",
      "OpenSearch",
      "Valkey",
      "Sequelize",
    ],
  },
  {
    label: "Architecture & Tooling",
    icon: "architecture",
    items: [
      "Microservices",
      "REST APIs",
      "GraphQL",
      "WebSocket",
      "WebRTC",
      "Grafana",
      "Prometheus",
      "Dynatrace",
      "Proxmox",
      "Swagger",
    ],
  },
  {
    label: "AI · IDEs · Models",
    icon: "sparkles",
    items: [
      "Cursor",
      "Devin",
      "OpenCode",
      "Windsurf",
      "GitHub Copilot",
      "Claude (Opus · Sonnet)",
      "Composer",
      "GPT",
      "Gemini",
      "Hugging Face",
    ],
  },
];
